'use client';

import { 
  BarChart3, 
  TrendingUp, 
  Eye, 
  Download, 
  FileText, 
  CheckCircle2, 
  Clock,
  Layout,
  ArrowUpRight,
  Target,
  PieChart,
  ShieldCheck,
  AlertCircle
} from 'lucide-react';
import { useProposalStore } from '../store/proposal-store';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/components/ui/card';
import { Badge } from '@/shared/components/ui/badge';
import { cn } from '@/shared/lib/utils';
import { PROPOSAL_TEMPLATES } from '../templates';

/**
 * Analytics Dashboard Component.
 * Provides high-fidelity insights into proposal generation and engagement.
 */
export function AnalyticsDashboard() {
  const { analytics, history } = useProposalStore();

  const stats = [
    {
      title: 'Total Proposals',
      value: analytics.totalGenerations,
      icon: FileText,
      color: 'text-blue-600',
      bg: 'bg-blue-50',
      description: 'Proposals generated by OpenClaw'
    },
    {
      title: 'Client Engagement',
      value: analytics.totalViews,
      icon: Eye,
      color: 'text-emerald-600',
      bg: 'bg-emerald-50',
      description: 'Total views across shared links'
    },
    {
      title: 'Document Exports',
      value: analytics.totalExports,
      icon: Download,
      color: 'text-amber-600',
      bg: 'bg-amber-50',
      description: 'PDF documents downloaded'
    },
    {
      title: 'Finalized Rate',
      value: `${analytics.totalGenerations > 0 ? Math.round((analytics.statusDistribution['finalized'] || 0) / analytics.totalGenerations * 100) : 0}%`,
      icon: Target,
      color: 'text-violet-600',
      bg: 'bg-violet-50',
      description: 'Conversion to finalized state'
    }
  ];

  // Calculate top template
  const topTemplateId = Object.entries(analytics.templateUsage)
    .sort(([, a], [, b]) => b - a)[0]?.[0];
  const topTemplate = PROPOSAL_TEMPLATES.find(t => t.id === topTemplateId);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat) => (
          <Card key={stat.title} className="border-none shadow-xl shadow-slate-200/50 rounded-3xl overflow-hidden hover:scale-[1.02] transition-transform duration-300">
            <CardContent className="p-6">
              <div className="flex justify-between items-start mb-4">
                <div className={cn("p-3 rounded-2xl", stat.bg)}>
                  <stat.icon className={cn("w-6 h-6", stat.color)} />
                </div>
                <Badge variant="outline" className="text-[10px] font-bold text-slate-400 border-slate-100">
                  Lifetime
                </Badge>
              </div>
              <div className="space-y-1">
                <h3 className="text-3xl font-black text-slate-900 tracking-tight">{stat.value}</h3>
                <p className="text-sm font-bold text-slate-500">{stat.title}</p>
              </div>
              <p className="text-[10px] text-slate-400 font-medium mt-4 uppercase tracking-wider">
                {stat.description}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Status Distribution (New) */}
        <Card className="lg:col-span-4 border-none shadow-xl shadow-slate-200/50 rounded-[2.5rem] overflow-hidden">
          <CardHeader className="p-8 border-b bg-slate-50/30">
            <CardTitle className="text-xl font-black flex items-center gap-2">
              <PieChart className="w-5 h-5 text-violet-500" /> Success Metrics
            </CardTitle>
            <CardDescription className="font-medium">Proposal lifecycle distribution.</CardDescription>
          </CardHeader>
          <CardContent className="p-8 space-y-6">
            <div className="space-y-4">
              {[
                { label: 'Draft', status: 'draft', icon: FileText, color: 'text-blue-500', bg: 'bg-blue-50' },
                { label: 'Finalized', status: 'finalized', icon: ShieldCheck, color: 'text-emerald-500', bg: 'bg-emerald-50' },
                { label: 'Expired', status: 'expired', icon: AlertCircle, color: 'text-rose-500', bg: 'bg-rose-50' },
              ].map((item) => {
                const count = analytics.statusDistribution[item.status] || 0;
                const percentage = analytics.totalGenerations > 0 ? (count / analytics.totalGenerations) * 100 : 0;
                return (
                  <div key={item.status} className="flex items-center gap-4">
                    <div className={cn("w-10 h-10 rounded-xl flex items-center justify-center shrink-0", item.bg)}>
                      <item.icon className={cn("w-5 h-5", item.color)} />
                    </div>
                    <div className="flex-1 space-y-1">
                      <div className="flex justify-between text-xs font-bold">
                        <span className="text-slate-600">{item.label}</span>
                        <span className="text-slate-900">{count} ({Math.round(percentage)}%)</span>
                      </div>
                      <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                        <div 
                          className={cn("h-full rounded-full transition-all duration-1000", item.color.replace('text', 'bg'))}
                          style={{ width: `${percentage}%` }}
                        />
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>

        {/* Template Usage Chart */}
        <Card className="lg:col-span-8 border-none shadow-xl shadow-slate-200/50 rounded-[2.5rem] overflow-hidden">
          <CardHeader className="p-8 border-b bg-slate-50/30">
            <div className="flex justify-between items-center">
              <div>
                <CardTitle className="text-xl font-black flex items-center gap-2">
                  <BarChart3 className="w-5 h-5 text-primary" /> Template Performance
                </CardTitle>
                <CardDescription className="font-medium">Which styles resonate most with your clients.</CardDescription>
              </div>
              {topTemplate && (
                <Badge className="bg-primary/10 text-primary border-none font-bold uppercase tracking-widest text-[10px] px-3 py-1">
                  Top: {topTemplate.name}
                </Badge>
              )}
            </div>
          </CardHeader>
          <CardContent className="p-8">
            <div className="space-y-6">
              {PROPOSAL_TEMPLATES.map((template) => {
                const count = analytics.templateUsage[template.id] || 0;
                const percentage = analytics.totalGenerations > 0 ? (count / analytics.totalGenerations) * 100 : 0;
                
                return (
                  <div key={template.id} className="space-y-2">
                    <div className="flex justify-between items-center">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-slate-900">{template.name}</span>
                        <Badge variant="outline" className="text-[8px] font-black uppercase tracking-tighter h-4 px-1 leading-none">
                          {template.style}
                        </Badge>
                      </div>
                      <span className="text-xs font-black text-slate-400">{count} usage{count !== 1 ? 's' : ''}</span>
                    </div>
                    <div className="h-3 w-full bg-slate-100 rounded-full overflow-hidden">
                      <div 
                        className="h-full bg-primary transition-all duration-1000 ease-out rounded-full"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Recent Engagement Feed */}
        <Card className="lg:col-span-12 border-none shadow-xl shadow-slate-200/50 rounded-[2.5rem] overflow-hidden">
          <CardHeader className="p-8 border-b bg-slate-50/30">
            <CardTitle className="text-xl font-black flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-emerald-500" /> Recent Engagement
            </CardTitle>
            <CardDescription className="font-medium">Real-time activity on your proposals.</CardDescription>
          </CardHeader>
          <CardContent className="p-8">
            <div className="space-y-6">
              {history.slice(0, 5).map((proposal) => (
                <div key={proposal.id} className="flex items-center gap-4 group">
                  <div className={cn(
                    "w-10 h-10 rounded-2xl flex items-center justify-center text-white shrink-0 shadow-lg",
                    proposal.stats.viewCount > 0 ? "bg-emerald-500 shadow-emerald-200" : "bg-slate-200 shadow-slate-100"
                  )}>
                    {proposal.stats.viewCount > 0 ? <Eye className="w-5 h-5" /> : <Clock className="w-5 h-5" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h4 className="text-sm font-black text-slate-900 truncate group-hover:text-primary transition-colors cursor-default">
                      {proposal.input.clientName}
                    </h4>
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                      {proposal.stats.viewCount} Views &bull; {proposal.stats.exportCount} Exports
                    </p>
                  </div>
                  <ArrowUpRight className="w-4 h-4 text-slate-300 group-hover:text-primary transition-colors" />
                </div>
              ))}
              
              {history.length === 0 && (
                <div className="text-center py-12 space-y-4">
                  <div className="w-12 h-12 rounded-full bg-slate-50 flex items-center justify-center mx-auto">
                    <Layout className="w-6 h-6 text-slate-200" />
                  </div>
                  <p className="text-sm font-bold text-slate-400">No activity recorded yet.</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
